sudo: required
services:
  - docker

before_install:
  - docker run -p 6379:6379 --name redis-server redis
  - docker build -t pmanole/redis-go-demo -f Dockerfile.dev .

script:
  - docker run pmanole/redis-go-demo go test -v ./...