sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t pmanole/redis-go-demo -f Dockerfile.dev .

script:
  - docker run pmanole/redis-go-demo go test -v ./...

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1' 
  app: 'docker-redis-go'
  env: 'Dockerredisgo-env-1'
  bucket_name: 'elasticbeanstalk-us-east-1-417789473161'
  bucket_path: 'docker-redis-go'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
