version: '3'
services:
  redis-server:
    image: "redis"
  golang-app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8081:8080"
    volumes:
      - .:/app
  tests:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    depends_on:
      - redis-server
    command: ["go", "test", "-v", "./..."]
